feat: added weekly goals & current month tracking

diff --git a/habit b/habit
--- a/habit
+++ b/habit
@@ -5,14 +5,9 @@ set -eo pipefail
 # set -x
 
 # colors
-declare black="\e[1;30m"
 declare red="\e[1;31m"
-declare green="\e[1;32m"
 declare yellow="\e[1;33m"
-declare blue="\e[1;34m"
-declare magenta="\e[1;35m"
 declare cyan="\e[1;36m"
-declare white="\e[1;37m"
 declare reset="\e[0m"
 
 # constants
@@ -56,28 +51,67 @@ x.add() {
   echo " ✨ Nice job! Added ${habit} to your tracking log..."
 }
 
-x.edit() { popup nvim "$HABIT_CONFIG_LOG"; }
+# Writes an weekly goal into the $HABIT_CONFIG_GOALS file
+#
+# habit - the habit being tracked
+# type - how the hours will be tracked ("weekly", "monthly")
+# hours - the number of hours to spent on a habit
+#
+# Note: I wont track monthly because I only need weekly; a feature to be
+# added.
+x.goal() {
+  local habit="${1}" hours="${2}" type="weekly"
 
-x.list.week() {
+  if [[ -z $habit ]] || [[ -z $hours ]] || [[ -z $type ]]; then
+    echo "Invalid arguments."
+    exit 1
+  fi
+
+  slug=$(echo "$habit" | slugify)
+
+  mkdir -p "$HABIT_CONFIG_DIR"
+  echo "${habit}|${hours}|${type}|${slug}" >>"$HABIT_CONFIG_GOALS"
+  echo " ✨ Tracking ${habit}! Added ${habit} to your goals log..."
+}
+
+x.edit.habits() { popup nvim "$HABIT_CONFIG_LOG"; }
+x.edit.goals() { popup nvim "$HABIT_CONFIG_GOALS"; }
+
+x.list() {
   local -A logs
   local -A habits
+  local -A goals
 
+  # process weekly goals
+  #
   while IFS="|" read -ra log; do
+    [[ -z "${log[0]}" ]] && continue
 
-    if [[ -z "${log[0]}" ]]; then
-      echo "Ooops, something went wrong!"
-      exit 1
+    habit="${log[0]}"
+    hours="${log[1]}"
+    type="${log[2]}"
+    slug="${log[3]}"
+
+    if [[ $type == "weekly" ]]; then
+      goals["${slug}.title"]=$habit
+      goals["${slug}.hours"]=$hours
     fi
+  done <"$HABIT_CONFIG_GOALS"
+
+  # process weekly habits
+  #
+  while IFS="|" read -ra log; do
+    [[ -z "${log[0]}" ]] && continue
 
     habit="${log[0]}"
     time="${log[1]}"
     date="${log[2]}"
     slug="${log[3]}"
 
-    weekNumber=$(gdate -d "$date" +"%V")
+    currentWeekNumber=$(gdate -d "$date" +"%V")
     weekDay=$(gdate -d "$date" +"%u")
 
-    index="${slug}.${weekNumber}.${weekDay}"
+    index="${slug}.${currentWeekNumber}.${weekDay}"
 
     count="${logs["${index}.count"]}"
 
@@ -100,14 +134,37 @@ x.list.week() {
       ((totalTimeInvested = currentTime + time))
 
       logs["${index}.count"]=$totalCounter
-      logs["${index}.time"]="$totalTimeInvested"
+      logs["${index}.time"]=$totalTimeInvested
 
     fi
 
   done <"$HABIT_CONFIG_LOG"
 
-  # 1..52
-  weekNumber=$(gdate +"%V")
+  currentWeekNumber=$(gdate +"%V")
+  currentWeekDay=$(gdate +"%u")
+
+  # get the total weekly invested
+  #
+  local -A totalInvested
+  for ((i = 1; i <= currentWeekDay; i++)); do
+    for slug in ${!habits[*]}; do
+      index="${slug}.${currentWeekNumber}.${i}"
+      count="${logs["${index}.count"]}"
+
+      [[ -z $count ]] && continue
+
+      time="${logs["${index}.time"]}"
+
+      currentTotalInvested="${totalInvested["${slug}"]}"
+
+      ((currentTotalInvested += time))
+
+      totalInvested["${slug}"]=$currentTotalInvested
+    done
+  done
+
+  # display the results
+  #
 
   padlimit=60
   pad=$(printf '%*s' "$padlimit")
@@ -147,8 +204,9 @@ x.list.week() {
       ;;
     esac
 
+    # Print all your tracked habits
     for slug in ${!habits[*]}; do
-      index="${slug}.${weekNumber}.${weekDay}"
+      index="${slug}.${currentWeekNumber}.${weekDay}"
 
       weekIndex="${logs["${index}.count"]}"
 
@@ -164,50 +222,76 @@ x.list.week() {
         printf " H: ${cyan}%s${reset}\n" "$time"
       fi
     done
+
+    # Print all your missing habits based on goals
+    if [[ "$weekDay" == "$currentWeekDay" ]]; then
+      for slug in ${!habits[*]}; do
+        index="${slug}.${currentWeekNumber}.${weekDay}"
+
+        title="${goals["${slug}.title"]}"
+        goalTime="${goals["${slug}.hours"]}"
+
+        timeInvested="${totalInvested["${slug}"]}"
+
+        if [[ -n $goalTime ]]; then
+          timeLeft=$(((goalTime - timeInvested)))
+          timeLeftInHours=$(bc <<<"scale=2; ${timeLeft}/60")
+
+          if [[ $timeLeft -gt 0 ]]; then
+            printf "   ${red}%s (n)${reset} " "$title"
+            printf "${red}%*.*s${reset}" 0 $((padlength - ${#title})) "$pad"
+            printf " ${red}H: %s${reset}\n" "$timeLeftInHours"
+          fi
+        fi
+      done
+    fi
+
   done
+
   printf "\n"
 }
 
-# todo make so that it only displays the current month
+# TODO: Track monthly instead of total
 x.list.month() {
   local -A logs
   local -A habits
 
   while IFS="|" read -ra log; do
 
-    if [[ -z "${log[0]}" ]]; then
-      echo "Ooops, something went wrong!"
-      exit 1
-    fi
+    [[ -z "${log[0]}" ]] && continue
 
     habit="${log[0]}"
     time="${log[1]}"
     date="${log[2]}"
     slug="${log[3]}"
 
-    count="${logs["${slug}.count"]}"
+    monthNumber=$(gdate -d "$date" +"%m")
+
+    index="${slug}.${monthNumber}"
+
+    count="${logs["${index}.count"]}"
 
     if [[ -z $count ]]; then
       # get update all the slugs
       habits["${slug}"]="$slug"
 
       # if there's no habit in the log array, initialize
-      logs["${slug}.count"]=1
-      logs["${slug}.title"]="$habit"
-      logs["${slug}.time"]="$time"
+      logs["${index}.count"]=1
+      logs["${index}.title"]="$habit"
+      logs["${index}.time"]="$time"
 
     else
       totalCounter=:
       totalTimeInvested=:
 
-      currentCounter="${logs["${slug}.count"]}"
-      currentTime="${logs["${slug}.time"]}"
+      currentCounter="${logs["${index}.count"]}"
+      currentTime="${logs["${index}.time"]}"
 
       ((totalCounter = currentCounter + 1))
       ((totalTimeInvested = currentTime + time))
 
-      logs["${slug}.count"]=$totalCounter
-      logs["${slug}.time"]="$totalTimeInvested"
+      logs["${index}.count"]=$totalCounter
+      logs["${index}.time"]="$totalTimeInvested"
     fi
   done <"$HABIT_CONFIG_LOG"
 
@@ -220,10 +304,15 @@ x.list.month() {
   printf "\n"
   echo -e "${yellow}This Month:${reset}"
 
+  currentMonth=$(gdate +"%m")
+
   for slug in ${!habits[*]}; do
-    title="${logs["${slug}.title"]}"
-    count="${logs["${slug}.count"]}"
-    time="${logs["${slug}.time"]}"
+
+    index="${slug}.${currentMonth}"
+
+    title="${logs["${index}.title"]}"
+    count="${logs["${index}.count"]}"
+    time="${logs["${index}.time"]}"
 
     time=$(bc <<<"scale=2; ${time}/60")
 
@@ -261,7 +350,11 @@ if [[ -n $COMP_LINE ]]; then
     for c in "${HABITS[@]}"; do
       [[ ${c:0:${#line}} == "${line}" ]] && echo "$c"
     done
-
+  elif [[ ${line,,} =~ goal ]]; then
+    line=${line//goal /}
+    for c in "${HABITS[@]}"; do
+      [[ ${c:0:${#line}} == "${line}" ]] && echo "$c"
+    done
   else
     for c in "${COMMANDS[@]}"; do
       [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
